// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wFFYvJ0IUMkvenNemKtq18FFOWakLhk',
    appId: '1:23135543888:android:ee196bdc708f557aa3e755',
    messagingSenderId: '23135543888',
    projectId: 'todo-c8220',
    storageBucket: 'todo-c8220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmzJNv_DAK_KRXZ-dBETQBBNGxNeFFOZE',
    appId: '1:23135543888:ios:c420fb7a3f9cce8ba3e755',
    messagingSenderId: '23135543888',
    projectId: 'todo-c8220',
    storageBucket: 'todo-c8220.appspot.com',
    iosBundleId: 'com.example.notificationsLesson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUmKgdpn15auscEQNJ-LbPnY_ua8wIKxE',
    appId: '1:23135543888:web:96c129dc531d7e5aa3e755',
    messagingSenderId: '23135543888',
    projectId: 'todo-c8220',
    authDomain: 'todo-c8220.firebaseapp.com',
    storageBucket: 'todo-c8220.appspot.com',
    measurementId: 'G-4TFHMGQVBP',
  );

}